perfetto: Disable rust target for trace proto on MCU's
Building //..." with "--config=rp2040" was giving:

> ERROR: toolchain type @@rules_rust_prost+//:toolchain_type resolved to
    target @@+pw_rust+pw_rust_toolchains//:prost_toolchain_impl, but
    that target does not provide ToolchainInfo

Test: Presubmit
Test: bazelisk build --config=rp2040 //... # Needs other patches
Test: bazelisk build --config=rp2350 //... # Needs other patches
Bug: b/485711443
Bug: b/461519669
Change-Id: I599bcc8e541c194031c5196d698dd0e1dbf6a85d
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/379974